[Eth]
NetworkId = 2151

[Node]
HTTPHost = "0.0.0.0"
HTTPPort = 8545
HTTPVirtualHosts = ["*"]
HTTPModules = ["eth", "net", "web3", "txpool"]

[Node.P2P]
BootstrapNodes = ["enode://5e2f2b95a570c377914e1ea8cba94bb023ceac82ee8708e56ac8d25a3242a0be33cedf9431a7df796dc03d0662c055a56e05c5fb36cdff80d73147b5849f2ad7@44.195.9.236:30301","enode://9e1b3f04581bde6d17203181cd261611eca2a35c83886989332dc6c3f4735e3f73be688f849c7328f6abbc8e9985fedc034778fe5ee5359e1e16e91f97c3703d@3.9.100.23:30301","enode://a46ab7ac08f632dd6bda071567c9d35c5749060264402e245106153030c14a2be7e020bba5c6b3f587a5cd9e5e5e1e408e7bb55946d8b40e71792d4f7bacf8a9@13.215.137.28:30301"]
StaticNodes = []
