[Eth]
NetworkId = 2019

[Node]
HTTPHost = "0.0.0.0"
HTTPPort = 8545
HTTPVirtualHosts = ["*"]
HTTPModules = ["eth", "net", "web3", "txpool"]

[Node.P2P]
BootstrapNodes = ["enode://71f11e735441a8740459e14ed47edacbdadbef0999763f5bfe7e777c9c7462fcec098c970e0c1e68a31d2922cfba2cd3293984c99103c45fc8cd85c32a992456@54.227.206.121:30301","enode://af5449967fba64172dff83e61a355a3aa0fec00acbdcd691fa9761e8db5110a8bab1f361f6763c1f6d74be1c002bea940b414978ffcc192baa397a31e752b78e@3.10.61.247:30301","enode://55e146a4de51b131eb2c09aac24b171813864ec55c4bff0f85233ef5b14fe81570abe0cd243666cd12347ad92aec01a7102869343b71ad76c78e852855e2e611@18.136.170.170:30301","enode://9559b5a3fc9e3195ece8ba5b2c7811bf60daa709e07e7ec2beabd6657380114bfccb929c34c001d5504280b82f6208910c536294178a8600d68fd281cf76c125@13.215.28.52:30301"]
StaticNodes = []
ListenAddr = ":30303"
